### ISSUE TITLE
How-to issue - Cannot add a new page

### ISSUE THREAD

**Issue by richh93** [ritenv/atwork#118]
I added a new page to the "posts" module (inside public-views) then added a route for it and then added a link to the page in index to be like the globe but instead of goHome for ng-click I had goToNewPage function and then added the function after goHome (in the same JS file), it's not working I even (as a test) edited the '/' route to go to a different page instead of feed.html and it still goes to feed.
Thanks

**Comment by ritenv** [comment]
You need to run `gulp` to build files. Hope that has solved it, already. Closing this.
